sudo: required
language: bash
services:
- docker
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t swestcott/rpi-telegraf:build .
- docker run swestcott/rpi-telegraf:build telegraf version
- VERSION=$(docker inspect --format '{{ range .Config.Env }}{{ println . }}{{ end
  }}' swestcott/rpi-telegraf:build | grep TELEGRAF_VERSION | sed 's/^.*=//')
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag swestcott/rpi-telegraf:build swestcott/rpi-telegraf:$VERSION
    docker tag swestcott/rpi-telegraf:build swestcott/rpi-telegraf:latest
    docker push swestcott/rpi-telegraf:$VERSION
    docker push swestcott/rpi-telegraf:latest
  fi
notifications:
  slack:
    secure: p95rj942KvUwPer5RdTrLc1pbXB2r1ToGDTXS4Gqgcd/MsaKj4xz22fnCl3pkBC7uOd+NA0EmthbLuNcYMJPn5la8am+2JEESQctbJC119+w1B8NOz/31vKZM75A9E5XIhMDDsuSnktACG+VoJt2orfOSY4lW4F0l80YvgK++IfZBdDECO+7aKY7T9tu9ZOnL6blWLi4XxMbbzdfVjehkpdAvsRxrO54zpSeShY1xVbnvEdWkxMNBUkiIDWoRQ22H9YwEsNOhEiqK/wmmRRJxdE96cjXhQ1xLWH/C8pxJNK3u7G6gVd05SPEMpRwWMWr++2b3LVY3JqLi9vVMDvrlyXJ5q5eBJG+aU2Nh4yoXBbIvLs4DkiWmiyv/vyLwTppqC7hgY+SFFDDIRPerIhVNFRwtRutCzG6e9/6ME1H6Qn9x+A2O3ZR76CK9nlPNgRiqDd6oLzhIn0xmhAUyzJn0XvuPJtSvQqR70EbAgvOO31DsyS856EWVqL0O1pTN2W4Nry4cYFhfcgnHvdmR7QfQus0M39g9W4X7B5gAezZScafVmxGp5W0LAD2DCSGNtKb48UI+RQzgXs91qRD8W9ts10D+/x1OUxsUErRXaowgJ0XFRC+jOUPmVKwzXaAMWIc5TK9u08ybAc81GXohAkDBQLKXhUM9zb90tXciw52p8I=
